### ISSUE TITLE
App crushes at photo editing 

### ISSUE THREAD

**Issue by V4kodin** [exteraSquad/exteraGram#51]
App crushes after i try to edit the photo.

1) Go to any dialogue.
2) Tap on clip
3) Tap on any photo
4) Tap on any editing function (like cropping or painting)
5) Crush

 - Device: Google Pixel 7
 - OS: Android 13
 - Version: 13 (TQ2A.230505.002)

Logs:

PerformClick.run

MethodAndArgsCaller.run

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.exteragram.messenger.camera.CameraXController.isFrontface()' on a null object reference
 at com.exteragram.messenger.camera.CameraXView.isFrontface(Unknown Source:2)
 at org.telegram.ui.Components.ChatAttachAlertPhotoLayout.onPhotoEditModeChanged(Unknown Source:14)
 at org.telegram.ui.Components.ChatAttachAlertPhotoLayout.-$$Nest$monPhotoEditModeChanged(SourceFile:0)
 at org.telegram.ui.Components.ChatAttachAlertPhotoLayout$1.onEditModeChanged(Unknown Source:2)
 at org.telegram.ui.PhotoViewer.switchToEditMode(Unknown Source:79)
 at org.telegram.ui.PhotoViewer.lambda$setParentActivity$26(Unknown Source:38)
 at org.telegram.ui.PhotoViewer.$r8$lambda$1ViugnzbJGpJg9P7k5v_t8Wcds8(SourceFile:0)
 at org.telegram.ui.PhotoViewer$$ExternalSyntheticLambda24.onClick(SourceFile:0)
 at android.view.View.performClick(View.java:7506)
 at android.view.View.performClickInternal(View.java:7483)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:29357)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7884)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by immat0x1** [comment]
@V4kodin install the latest beta from ci channel

**Comment by V4kodin** [comment]
> @V4kodin install the latest beta from ci channel

Works for me thx.
