### ISSUE TITLE
Crash (IndexOutOfBounds)

### ISSUE THREAD

**Issue by ghost** [exteraSquad/exteraGram#61]
**Describe the bug**
Crash when long pressing on the user's name in the profile

**To Reproduce**
1. Go to any user/channel/chat profile
2. Long press on the Name (not username)
3. See error

**Smartphone:**
 - Device: Google Pixel 4
 - OS: Android 13
 - Version: 10.5.0 (42289)

♥️ Happy New Year!

**Comment by thedeaddan** [comment]
Error:
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at org.telegram.ui.ProfileActivity$23.performLongClick(Unknown Source:189)
	at android.view.View$CheckForLongPress.run(View.java:30849)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
